Test validate branch

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -10,7 +10,19 @@ on:
         required: true
 
 jobs:
+  validate:
+    name: Validating Branch Name
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate branch name
+        run: |
+          if ! [[ "${{ github.event.inputs.pr_branch }}" =~ (?i)^(feature|bugfix|techdebt)/.* ]]; then
+            echo "Invalid branch name. Must start with feature/, bugfix/, or techdebt/"
+            exit 1
+          fi
+
   GetData:
+    name: Build Docker Image for ${{ github.event.inputs.instance }}
     runs-on: ubuntu-latest
     environment:
       name: dev
